on:
  push:
    branches: [main]

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    name: Build and Upload Publications PDF
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: src
        args: -outdir=../build
    - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build