on:
  schedule:
    - cron: "0 0 1 * *" # Run at 00:00 on the first day of each month
  push:
    branches: [main]

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    name: Build and Upload Publications PDF
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Query DBLP Publications
      run: python scripts/dblp.py
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        args: -outdir=../build -pdf
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build